
backend:
  name: git-gateway
  branch: master
media_folder: /
publish_mode: editorial_workflow
media_library:
  name: cloudinary
  config:
    multiple: true
    cloud_name: ddio9vlzi
    api_key: 868348336488664

collections:
  - name: auteurs
    label: Auteurs
    folder: "content/auteurs"
    create: true
    fields:
      - {name: naam, label: Naam}

  - name: tags
    label: Tags
    folder: "content/tags"
    create: true
    fields:
      - {name: naam, label: Naam}

  - name: photo's
    label: Photo's
    folder: "content/photo's"
    create: true
    fields:
      - {name: onderschrift, label: Onderschrift,required: true}
      - {name: bron, label: Bron,required: false}
      - {label: "Image", name: "image", widget: "image",required: true}

  - name: posts
    label: Posts
    folder: "content/posts"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post.template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "Subtitle", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: 'HeaderPhoto name', name: 'headerPhoto name', widget: 'string'}
      - label: 'HeaderPhoto'
        name: 'headerPhoto'
        widget: 'image'
        tagname: ''
        allow_multiple: false


      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Onderwerp"
        name: "onderwerp"
        widget: "select"
        options: ["history","human","nature","quirky","space","tech"]
      - name: auteur
        label: Auteur
        widget: relation
        collection: auteurs
        searchFields: [naam]
        valueField: naam
      - name: tags
        label: Tags
        widget: relation
        collection: tags
        searchFields: [naam]
        multiple: true
        valueField: naam
        required: false
      - name: photo's
        label: Photo's
        widget: relation
        collection: photo's
        searchFields: [onderschrift]
        display_fields: [onderschrift]
        multiple: true
        valueField: "{{slug}}"
        required: false
        options_length: 1
      - { label: 'Id', name: 'id', widget: uuid }
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        default: []

