
backend:
  name: git-gateway
  branch: master
media_folder: /
publish_mode: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: ddio9vlzi
    api_key: 868348336488664

collections:
  - name: auteurs
    label: Auteurs
    folder: "content/auteurs"
    create: true
    fields:
      - {name: naam, label: Naam}

  - name: tags
    label: Tags
    folder: "content/tags"
    create: true
    fields:
      - {name: naam, label: Naam}

  - name: photo's
    label: Photo's
    folder: "content/photo's"
    create: true
    fields:
      - {name: onderschrift, label: Onderschrift,required: true}
      - {name: bron, label: Bron,required: false}
      - {label: "Image", name: "image", widget: "image",required: true}

  - name: posts
    label: Posts
    folder: "content/posts"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post.template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "Subtitle", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - name: headerPhoto
        label: HeaderPhoto
        widget: relation
        collection: photo's
        searchFields: [image,onderschrift]
        required: true
        display_fields: [onderschrift]
        value_field: "image"
        options_length: 3
        allow_multiple: false
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Onderwerp"
        name: "onderwerp"
        widget: "select"
        options: ["history","human","nature","quirky","space","tech"]
      - name: auteur
        label: Auteur
        widget: relation
        collection: auteurs
        search_fields: [naam]
        value_field: naam
      - { label: 'Id', name: 'id', widget: uuid }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: Tag, name: tag, widget: string}